# Generated by Django 3.2.19 on 2023-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyticsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('time', models.DateTimeField(blank=True, verbose_name='Time')),
                ('total_view_count', models.PositiveIntegerField(default=0, verbose_name='Total View Count')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
