# Generated by Django 3.2.19 on 2023-07-20 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230721_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdata',
            name='time',
            field=models.CharField(default=datetime.datetime(2023, 7, 20, 22, 19, 40, 238335, tzinfo=utc), max_length=100),
        ),
    ]
