# Generated by Django 3.2.19 on 2023-07-20 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_analyticsdata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtimedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP Address')),
                ('time', models.CharField(default=datetime.datetime(2023, 7, 20, 22, 42, 52, 377031, tzinfo=utc), max_length=100)),
                ('total_view_count', models.PositiveIntegerField(default=0, verbose_name='Total View Count')),
            ],
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='time',
            field=models.CharField(default=datetime.datetime(2023, 7, 20, 22, 42, 52, 295260, tzinfo=utc), max_length=100),
        ),
    ]
